### ISSUE TITLE
Rendering of spots on the fish is very slow

### ISSUE THREAD

**Issue by dattasid** [LingDong-/fishdraw#1]
Some fish are generated with tiny spots on them. When that happens rendering is slowed a lot.

Maybe a simpler method can be used for drawing them.

**Comment by LingDong-** [comment]
Thanks for the issue! Yes the dots are kinda slow because they use poisson disk sampling to have relatively uniform spacing. I just added a small optimization ff2abc9a2d7e87f3a22b4648e68f77b75a5a4c05 to only compute the dots within the bounding box of the given shape, which should make it a bit faster.

**Comment by dattasid** [comment]
Awesome!
